In [18]:
def readFasta(filename):
    sequences = []
    
    with open(filename) as fh:
        while True:
            fh.readline()
            seq = fh.readline().rstrip()
            fh.readline()
            if len(seq) == 0:
                break
            sequences.append(seq)
            
        return sequences

In [19]:
seqs = readFasta('TESTT.txt')
class1_1 =  ''.join(seqs)

In [20]:
dnadata = [{'sequence': class1_1 , 'class': 2}]

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
df = pd.DataFrame(dnadata)


In [22]:
df

class                                           sequence
0      2  TAGCGCTGCTAGTCGATCGTAGCTGATGCTGATGCTCGCTCGCTAG...

In [23]:
# function to convert sequence strings into k-mer words, default size = 8 (hexamer words)
def getKmers(sequence, size=4):
    return [sequence[x:x+size].lower() for x in range(len(sequence) - size + 1)]

In [24]:
df['words'] = df.apply(lambda x: getKmers(x['sequence']), axis=1)
df = df.drop('sequence', axis=1)
df

class                                              words
0      2  [tagc, agcg, gcgc, cgct, gctg, ctgc, tgct, gct...

In [25]:
df_texts = list(df['words'])
for item in range(len(df_texts)):
    df_texts[item] = ' '.join(df_texts[item])
y_h = df.iloc[:, 0].values               

df_texts

['tagc agcg gcgc cgct gctg ctgc tgct gcta ctag tagt agtc gtcg tcga cgat gatc atcg tcgt cgta gtag tagc agct gctg ctga tgat gatg atgc tgct gctg ctga tgat gatg atgc tgct gctc ctcg tcgc cgct gctc ctcg tcgc cgct gcta ctag tagg agga ggag gaga agag gaga agag gaga agag gagg agga ggag gaga agag gaga agag gaga agag gagt agta gtag taga agag gaga agag gaga agag gaga agag gaga agac gaca acag cagc agca gcag caga agac gacg acga cgac gaca acat cata atag taga agag gaga agag gaga agag gaga agag gagt agtg gtga tgac gacc accg ccga cgat gatg atga tgag gaga agac gacc acca ccag caga agag gagg aggg ggga ggag gagg aggg gggg gggg gggg gggg ggga ggag gaga agag gaga agag gagg aggg gggg gggg gggg gggg gggc ggcg gcgc cgct gctc ctcc tcct cctt cttc ttct tctt cttc ttct tctc ctct tctt cttt tttt tttt tttt tttc ttct tctc ctct tctt cttt tttt tttt tttt tttt tttt tttt tttc ttct tctt cttc ttct tctt cttt tttt ttta ttat tata atat tata atat tatt atta ttat tata atat tata ataa taaa aaaa aaaa aaaa aaaa aaat aata atat tata atat tat

In [26]:
y_h

array([2])

In [27]:
import pickle

pickled_model, cv = pickle.load(open("tuple_model-Copy1.pkl", 'rb'))  


In [28]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
# load the model from disk

X_test = cv.transform(df_texts)



In [29]:
pickled_model

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [30]:
print(X_test.shape)

(1, 13503)


In [31]:
pred = pickled_model.predict(X_test)
pred

array([0])

In [32]:
pred[0]

0

In [33]:
xxx = pickled_model.predict_log_proba(X_test)
xxx

array([[     0.        , -51781.21654723]])

In [16]:
xxxx = xxx[0]
xxxx

array([-184209.35549316,       0.        ])

In [17]:
aaa = xxxx[0]
aaa

-184209.35549316136

In [18]:
bbb = xxxx[1]
bbb

0.0

In [19]:
my_string_date = str(aaa).replace('-', '')
my_string_date = str(my_string_date).replace('.', '')

my_string_date = my_string_date

In [20]:
my_string_date

'18420935549316136'

In [21]:
my_string_date1 = '0.'+my_string_date

In [22]:
my_string_date1

'0.18420935549316136'